### ISSUE TITLE
Implement storing of drag-n-drop order in Dashboard.

### ISSUE THREAD

**Issue by pxamike** [pixelant/dashboard#3]
Currently you can drag and drop the order of the widgets. However, it is not stored/updated. Instead you can access "Dashboard settings" and in that interface move widgets up or down in the list to affect the ordering. My suggestion is to implement a saving mechanism (if the updated order is stored, there's a point in having the drag-n-drop feature in the first place).

If that's not possible for now, drag and drop should be disabled, to not imply a feature that doesn't really work.

**Comment by pixelmatseriks** [comment]
Fixed in release 8.0.0
